# Docker compose for latest container build (khafidprayoga/todoapp-fiber)
# After running compose, create .env and start migrate up data and call Seed()
# and run command `go run play/play.go` on root project structure
version: '3.3'
services:
  backend:
    image: khafidprayoga/todoapp-fiber
    restart: on-failure
    environment:
      PRODUCTION: "1"
      APP_DEBUG: "0"
      MYSQL_HOST: "db"
      MYSQL_PORT: "3306"
      MYSQL_USER: "fiber"
      MYSQL_PASSWORD: "fiber"
      MYSQL_DBNAME: "todolist-app"
    links:
      - "db"
    ports:
      - '8090:3030'

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'todolist-app'
      MYSQL_USER: 'fiber'
      MYSQL_PASSWORD: 'fiber'
      MYSQL_ROOT_PASSWORD: 'root'
    expose:
      - '3306'
    volumes:
      - mysql-todoapp-db:/var/lib/mysql

volumes:
  mysql-todoapp-db:

